from pptx import Presentation
from pptx.util import Inches
from docx import Document
from docx.shared import Inches as DocxInches
import tempfile
import os

def create_powerpoint(gpt_summary, float_fig, milestone_fig, title="Delay Impact Analysis"):
    prs = Presentation()

    slide = prs.slides.add_slide(prs.slide_layouts[0])
    slide.shapes.title.text = title
    slide.placeholders[1].text = "Auto-generated by Scenario Simulation Assistant"

    slide = prs.slides.add_slide(prs.slide_layouts[1])
    slide.shapes.title.text = "AI Summary"
    slide.placeholders[1].text = gpt_summary

    # Save temporary images
    temp_dir = tempfile.mkdtemp()
    float_img_path = os.path.join(temp_dir, "float_chart.png")
    milestone_img_path = os.path.join(temp_dir, "milestone_chart.png")
    float_fig.savefig(float_img_path, bbox_inches='tight')
    milestone_fig.savefig(milestone_img_path, bbox_inches='tight')

    slide = prs.slides.add_slide(prs.slide_layouts[5])
    slide.shapes.title.text = "Float Change Chart"
    slide.shapes.add_picture(float_img_path, Inches(1), Inches(1.5), width=Inches(8))

    slide = prs.slides.add_slide(prs.slide_layouts[5])
    slide.shapes.title.text = "Milestone Shifts"
    slide.shapes.add_picture(milestone_img_path, Inches(1), Inches(1.5), width=Inches(8))

    pptx_path = os.path.join(temp_dir, "Delay_Impact_Analysis_PPTX.pptx")
    prs.save(pptx_path)
    return pptx_path

def create_word_doc(gpt_summary, float_fig, milestone_fig, title="Delay Impact Report"):
    doc = Document()
    doc.add_heading(title, 0)
    doc.add_paragraph("Auto-generated by Scenario Simulation Assistant")

    doc.add_heading("AI Summary", level=1)
    for line in gpt_summary.split("\n"):
        doc.add_paragraph(line)

    # Save temporary images
    temp_dir = tempfile.mkdtemp()
    float_img_path = os.path.join(temp_dir, "float_chart.png")
    milestone_img_path = os.path.join(temp_dir, "milestone_chart.png")
    float_fig.savefig(float_img_path, bbox_inches='tight')
    milestone_fig.savefig(milestone_img_path, bbox_inches='tight')

    doc.add_page_break()
    doc.add_heading("Float Change Chart", level=1)
    doc.add_picture(float_img_path, width=DocxInches(6))

    doc.add_page_break()
    doc.add_heading("Milestone Shifts", level=1)
    doc.add_picture(milestone_img_path, width=DocxInches(6))

    word_path = os.path.join(temp_dir, "Delay_Impact_Report_Word.docx")
    doc.save(word_path)
    return word_path
